apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{ .Values.app }}
  type: ClusterIP
